# Generated by Django 4.1.3 on 2025-08-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_blood_group_user_current_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bio',
            new_name='social_media',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='O+', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.DeleteModel(
            name='UserContact',
        ),
    ]
