# Generated by Django 4.1.3 on 2025-09-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='regKeyId',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
