# Generated by Django 4.1.3 on 2025-09-19 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_emailotp_regkeyid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailotp',
            name='regKeyId',
        ),
    ]
