# Generated by Django 4.1.3 on 2025-09-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_emailotp_regkeyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='regKey',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
