# Generated by Django 4.1.3 on 2025-09-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_emailotp_regkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailotp',
            name='regKey',
        ),
        migrations.AddField(
            model_name='emailotp',
            name='regKeyId',
            field=models.IntegerField(null=True),
        ),
    ]
