# Generated by Django 4.1.3 on 2025-09-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_emailotp_regkey_emailotp_regkeyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
