# Generated by Django 4.1.3 on 2025-09-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_emailotp_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('verified', models.BooleanField(default=False)),
                ('registrationKey', models.CharField(max_length=8)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='EmailOTP',
        ),
        migrations.DeleteModel(
            name='RegistrationKey',
        ),
    ]
