# Generated by Django 4.1.3 on 2025-09-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_registration_delete_emailotp_delete_registrationkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='otp',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
