# Generated by Django 4.1.3 on 2025-09-22 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_registration_email_alter_registration_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='verified',
        ),
    ]
