# Generated by Django 4.1.3 on 2025-09-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('Civil Eng.', 'Civil Eng.'), ('Architectural Eng.', 'Architectural Eng.'), ('Environmental Eng.', 'Environmental Eng.'), ('Mechanical Eng.', 'Mechanical Eng.'), ('Chemical Eng.', 'Chemical Eng.'), ('Food Eng.', 'Food Eng.'), ('Electrical Eng.', 'Electrical Eng.'), ('Electronics Eng.', 'Electronics Eng.'), ('Computer Eng.', 'Computer Eng.'), ('Power Eng.', 'Power Eng.'), ('Automobile Eng.', 'Automobile Eng.'), ('RAC Eng.', 'RAC Eng.')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='job_type',
            field=models.CharField(blank=True, choices=[('Government', 'Government'), ('Private', 'Private'), ('Bussiness', 'Bussiness'), ('Homemaker', 'Homemaker'), ('Others', 'Others')], max_length=10, null=True),
        ),
    ]
